# 01 Importing Libraries

In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

In [2]:
path = r'/Users/Dena/Instacart Basket Analysis'

In [3]:
# import merged data
df_merged = pd.read_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_merged_new.pkl'))

# check the output
df_merged.head()

,order_id,user_id,number_of_orders_by_user,orders_day_of_week,order_hour_of_day,days_since_prior_order,is_first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,price_range_loc,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders
1,2398795,1,2,3,7,15.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders
2,473747,1,3,3,12,21.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders
4,431534,1,5,4,15,28.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders

In [4]:
# create a subet of the merged data frame
df = df_merged[:1000000]

In [5]:
# check its shape
df.shape

(1000000, 18)

In [17]:
# check the output
df.head(30)

,order_id,user_id,number_of_orders_by_user,orders_day_of_week,order_hour_of_day,days_since_prior_order,is_first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,price_range_loc,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders
1,2398795,1,2,3,7,15.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders
2,473747,1,3,3,12,21.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders
4,431534,1,5,4,15,28.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders
5,3367565,1,6,2,7,19.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders
6,550135,1,7,1,9,20.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
7,3108588,1,8,1,14,14.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
8,2295261,1,9,1,16,0.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
9,2550362,1,10,4,8,30.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders
10,2968173,15,15,1,9,7.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
11,1870022,15,17,2,16,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders
12,1911383,15,18,2,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders
13,2715276,15,21,1,9,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
14,487368,15,22,1,10,14.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
15,2293453,19,2,5,14,6.0,No,196,3,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders
16,1973799,19,5,6,12,8.0,No,196,15,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders
17,532817,19,7,4,17,6.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders
18,1573906,21,10,3,10,6.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders
19,1593000,31,10,3,8,7.0,No,196,17,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders
20,2231262,31,17,3,11,8.0,No,196,14,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders
21,2580647,43,6,4,16,4.0,No,196,9,0,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders
22,2187180,43,9,4,12,3.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders
23,2497897,52,1,1,9,NaN,Yes,196,4,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
24,1318871,52,2,1,10,7.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
25,1261384,52,3,1,10,7.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
26,580568,52,5,2,10,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders
27,2428073,52,7,2,7,8.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders
28,342306,52,9,1,11,7.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders
29,1520353,52,10,2,10,8.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders

# 02 Grouping and Aggregating Data

In [7]:
# try the groupby() function (split the data into groups)
df.groupby('product_name')

In [14]:
# aggregate the data
df.groupby('department_id').agg({'number_of_orders_by_user': ['mean']})

              number_of_orders_by_user
                                  mean
department_id
4                            18.825780
7                            17.472355
13                           17.993423
14                           19.246334
16                           19.463012
17                           11.294069
19                           19.305237
20                           17.599636

In [16]:
# same results, different method
df.groupby('department_id')['number_of_orders_by_user'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: number_of_orders_by_user, dtype: float64

In [19]:
# We can also use this code, but it is better to use brackets for indexing!
df.groupby('department_id').number_of_orders_by_user.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: number_of_orders_by_user, dtype: float64

In [20]:
# multiple aggregations

df.groupby('department_id').agg({'number_of_orders_by_user': ['mean', 'min', 'max']})

              number_of_orders_by_user
                                  mean min max
department_id
4                            18.825780   1  99
7                            17.472355   1  99
13                           17.993423   1  99
14                           19.246334   1  99
16                           19.463012   1  99
17                           11.294069   1  98
19                           19.305237   1  99
20                           17.599636   1  99

In [21]:
# criteria for our flag:

# If the maximum orders the user has made is over 40, then the customer will be labeled a “Loyal customer.”
# ...over 10 but less than or equal to 40, then the customer will be labeled a “Regular customer.”
# ...less than or equal to 10, then the customer will be labeled a “New customer.”

In [25]:
# create a new max_order column
df_merged['max_order'] = df_merged.groupby(['user_id'])['number_of_orders_by_user'].transform(np.max)

In [24]:
# check the output
df_merged.head(15)

,order_id,user_id,number_of_orders_by_user,orders_day_of_week,order_hour_of_day,days_since_prior_order,is_first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,10
1,2398795,1,2,3,7,15.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,10
5,3367565,1,6,2,7,19.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,10
6,550135,1,7,1,9,20.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders,10
10,2968173,15,15,1,9,7.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,22
12,1911383,15,18,2,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,22
13,2715276,15,21,1,9,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22

In [26]:
# change the settings so Jupyter displays all the rows you want

pd.options.display.max_rows = None

In [28]:
# check the output

df_merged.head(100)

,order_id,user_id,number_of_orders_by_user,orders_day_of_week,order_hour_of_day,days_since_prior_order,is_first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,10
1,2398795,1,2,3,7,15.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,10
5,3367565,1,6,2,7,19.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,10
6,550135,1,7,1,9,20.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders,10
10,2968173,15,15,1,9,7.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,22
12,1911383,15,18,2,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,22
13,2715276,15,21,1,9,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,No,196,3,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,9
16,1973799,19,5,6,12,8.0,No,196,15,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,9
17,532817,19,7,4,17,6.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,9
18,1573906,21,10,3,10,6.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,33
19,1593000,31,10,3,8,7.0,No,196,17,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,20
20,2231262,31,17,3,11,8.0,No,196,14,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,20
21,2580647,43,6,4,16,4.0,No,196,9,0,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,11
22,2187180,43,9,4,12,3.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,11
23,2497897,52,1,1,9,NaN,Yes,196,4,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
27,2428073,52,7,2,7,8.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,27
28,342306,52,9,1,11,7.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
30,2542086,52,11,2,9,7.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
31,944694,52,12,1,16,6.0,No,196,7,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
33,1122089,52,17,2,10,6.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
34,1498922,52,18,2,10,14.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
35,180919,52,19,3,8,8.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,27
36,2695875,52,21,5,10,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27
37,3205960,67,1,3,11,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,24
38,970922,67,2,1,15,5.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24
41,2474111,67,5,3,14,8.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,24
42,1568481,67,6,3,12,7.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,24
43,2048527,67,8,2,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24
44,2389031,67,9,2,14,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24
45,2378562,67,10,1,10,6.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24
48,1949274,67,13,1,10,6.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
50,768572,67,16,4,10,9.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,24
51,150528,67,18,5,16,4.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24
52,29758,67,19,0,14,9.0,No,196,2,1,Soda,77,7,9.0,Busiest day,Mid-range product,Busiest days,Most orders,24
53,1558976,67,21,1,9,5.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
54,863974,67,22,1,11,14.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
55,2308399,67,23,1,14,14.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24
56,2759128,81,3,1,9,14.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,7
57,1812985,81,5,2,20,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,7
58,1889835,82,1,3,15,NaN,Yes,196,6,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,19
59,499460,82,3,5,10,5.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19
60,2728456,82,4,0,11,16.0,No,196,1,1,Soda,77,7,9.0,Busiest day,Mid-range product,Busiest days,Most orders,19
61,2653743,82,6,4,9,13.0,No,196,5,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,19
62,1358880,82,9,1,10,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,19
63,343588,82,10,2,11,1.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19
64,3034663,82,15,2,11,12.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19
65,147262,82,18,1,13,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,19
66,3144004,82,19,2,15,8.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19
67,2126069,98,3,0,9,25.0,No,196,7,0,Soda,77,7,9.0,Busiest day,Mid-range product,Busiest days,Most orders,14
68,2210120,98,7,5,14,5.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,14
69,681011,98,9,3,9,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,14
70,2846344,98,11,4,13,15.0,No,196,2,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,14
71,747431,98,12,6,13,30.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,14
72,2383054,98,13,4,11,30.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,14
73,1993729,98,14,5,8,8.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,14
74,1403849,109,3,3,17,9.0,No,196,5,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,6
75,520620,120,1,3,11,NaN,Yes,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,3
76,3273029,120,3,2,8,19.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,3
77,1861943,185,2,1,12,25.0,No,196,10,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,6
78,2040988,195,1,1,14,NaN,Yes,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,58
79,1680569,195,8,1,9,4.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,58
80,276171,195,19,5,11,3.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58
81,2744976,195,22,5,10,7.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58
82,2781919,195,25,1,14,4.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,58
83,1738718,195,31,2,8,4.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,58
84,3058369,195,34,3,10,6.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,58
85,1485596,195,37,2,15,0.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58
86,417035,195,40,3,16,2.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,58
87,1615297,195,47,5,10,2.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58
88,1765587,195,52,3,12,2.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,58
89,745908,195,57,4,11,3.0,No,196,3,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,58
90,2505656,222,17,2,12,1.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,70
91,3268370,222,38,5,15,1.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,70
92,2016711,290,9,5,19,6.0,No,196,8,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,51
93,2706088,290,28,6,10,7.0,No,196,16,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,51
94,1952286,331,6,5,16,30.0,No,196,8,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,8
95,3226575,360,1,5,12,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,3
96,1469869,377,3,5,17,3.0,No,196,9,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,3
97,1927023,387,2,4,10,22.0,No,196,3,0,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,8
98,858092,420,4,1,19,30.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,22

In [31]:
# create a flag column

df_merged.loc[df_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [32]:
df_merged.loc[(df_merged['max_order'] <= 40) & (df_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [33]:
df_merged.loc[df_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [36]:
df_merged.head(100)

,order_id,user_id,number_of_orders_by_user,orders_day_of_week,order_hour_of_day,days_since_prior_order,is_first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,busiest_day,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,10,New customer
1,2398795,1,2,3,7,15.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,10,New customer
2,473747,1,3,3,12,21.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,10,New customer
3,2254736,1,4,4,7,29.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders,10,New customer
4,431534,1,5,4,15,28.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,10,New customer
5,3367565,1,6,2,7,19.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,10,New customer
6,550135,1,7,1,9,20.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10,New customer
7,3108588,1,8,1,14,14.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10,New customer
8,2295261,1,9,1,16,0.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,10,New customer
9,2550362,1,10,4,8,30.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Average orders,10,New customer
10,2968173,15,15,1,9,7.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22,Regular customer
11,1870022,15,17,2,16,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,22,Regular customer
12,1911383,15,18,2,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,22,Regular customer
13,2715276,15,21,1,9,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22,Regular customer
14,487368,15,22,1,10,14.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,22,Regular customer
15,2293453,19,2,5,14,6.0,No,196,3,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,9,New customer
16,1973799,19,5,6,12,8.0,No,196,15,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,9,New customer
17,532817,19,7,4,17,6.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,9,New customer
18,1573906,21,10,3,10,6.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,33,Regular customer
19,1593000,31,10,3,8,7.0,No,196,17,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,20,Regular customer
20,2231262,31,17,3,11,8.0,No,196,14,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,20,Regular customer
21,2580647,43,6,4,16,4.0,No,196,9,0,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,11,Regular customer
22,2187180,43,9,4,12,3.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,11,Regular customer
23,2497897,52,1,1,9,NaN,Yes,196,4,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27,Regular customer
24,1318871,52,2,1,10,7.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27,Regular customer
25,1261384,52,3,1,10,7.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27,Regular customer
26,580568,52,5,2,10,8.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
27,2428073,52,7,2,7,8.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,27,Regular customer
28,342306,52,9,1,11,7.0,No,196,5,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27,Regular customer
29,1520353,52,10,2,10,8.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
30,2542086,52,11,2,9,7.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
31,944694,52,12,1,16,6.0,No,196,7,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,27,Regular customer
32,1268191,52,15,2,11,8.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
33,1122089,52,17,2,10,6.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
34,1498922,52,18,2,10,14.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
35,180919,52,19,3,8,8.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,27,Regular customer
36,2695875,52,21,5,10,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,27,Regular customer
37,3205960,67,1,3,11,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,24,Regular customer
38,970922,67,2,1,15,5.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
39,596585,67,3,1,13,7.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
40,2037087,67,4,2,9,8.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24,Regular customer
41,2474111,67,5,3,14,8.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,24,Regular customer
42,1568481,67,6,3,12,7.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,24,Regular customer
43,2048527,67,8,2,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24,Regular customer
44,2389031,67,9,2,14,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24,Regular customer
45,2378562,67,10,1,10,6.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
46,1515698,67,11,1,11,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
47,1928050,67,12,2,12,8.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24,Regular customer
48,1949274,67,13,1,10,6.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
49,551869,67,14,1,9,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
50,768572,67,16,4,10,9.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,24,Regular customer
51,150528,67,18,5,16,4.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,24,Regular customer
52,29758,67,19,0,14,9.0,No,196,2,1,Soda,77,7,9.0,Busiest day,Mid-range product,Busiest days,Most orders,24,Regular customer
53,1558976,67,21,1,9,5.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
54,863974,67,22,1,11,14.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
55,2308399,67,23,1,14,14.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,24,Regular customer
56,2759128,81,3,1,9,14.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,7,New customer
57,1812985,81,5,2,20,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,7,New customer
58,1889835,82,1,3,15,NaN,Yes,196,6,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,19,Regular customer
59,499460,82,3,5,10,5.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19,Regular customer
60,2728456,82,4,0,11,16.0,No,196,1,1,Soda,77,7,9.0,Busiest day,Mid-range product,Busiest days,Most orders,19,Regular customer
61,2653743,82,6,4,9,13.0,No,196,5,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,19,Regular customer
62,1358880,82,9,1,10,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,19,Regular customer
63,343588,82,10,2,11,1.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19,Regular customer
64,3034663,82,15,2,11,12.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19,Regular customer
65,147262,82,18,1,13,7.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,19,Regular customer
66,3144004,82,19,2,15,8.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,19,Regular customer
67,2126069,98,3,0,9,25.0,No,196,7,0,Soda,77,7,9.0,Busiest day,Mid-range product,Busiest days,Most orders,14,Regular customer
68,2210120,98,7,5,14,5.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,14,Regular customer
69,681011,98,9,3,9,30.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,14,Regular customer
70,2846344,98,11,4,13,15.0,No,196,2,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,14,Regular customer
71,747431,98,12,6,13,30.0,No,196,4,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,14,Regular customer
72,2383054,98,13,4,11,30.0,No,196,1,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,14,Regular customer
73,1993729,98,14,5,8,8.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,14,Regular customer
74,1403849,109,3,3,17,9.0,No,196,5,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,6,New customer
75,520620,120,1,3,11,NaN,Yes,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,3,New customer
76,3273029,120,3,2,8,19.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,3,New customer
77,1861943,185,2,1,12,25.0,No,196,10,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,6,New customer
78,2040988,195,1,1,14,NaN,Yes,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,58,Loyal customer
79,1680569,195,8,1,9,4.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,58,Loyal customer
80,276171,195,19,5,11,3.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58,Loyal customer
81,2744976,195,22,5,10,7.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58,Loyal customer
82,2781919,195,25,1,14,4.0,No,196,1,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Most orders,58,Loyal customer
83,1738718,195,31,2,8,4.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,58,Loyal customer
84,3058369,195,34,3,10,6.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,58,Loyal customer
85,1485596,195,37,2,15,0.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58,Loyal customer
86,417035,195,40,3,16,2.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,58,Loyal customer
87,1615297,195,47,5,10,2.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,58,Loyal customer
88,1765587,195,52,3,12,2.0,No,196,3,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Most orders,58,Loyal customer
89,745908,195,57,4,11,3.0,No,196,3,1,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,58,Loyal customer
90,2505656,222,17,2,12,1.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,70,Loyal customer
91,3268370,222,38,5,15,1.0,No,196,6,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,70,Loyal customer
92,2016711,290,9,5,19,6.0,No,196,8,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Average orders,51,Loyal customer
93,2706088,290,28,6,10,7.0,No,196,16,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,51,Loyal customer
94,1952286,331,6,5,16,30.0,No,196,8,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,8,New customer
95,3226575,360,1,5,12,NaN,Yes,196,1,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,3,New customer
96,1469869,377,3,5,17,3.0,No,196,9,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Regular days,Most orders,3,New customer
97,1927023,387,2,4,10,22.0,No,196,3,0,Soda,77,7,9.0,Least busy,Mid-range product,Slowest days,Most orders,8,New customer
98,858092,420,4,1,19,30.0,No,196,2,0,Soda,77,7,9.0,Regularly busy,Mid-range product,Busiest days,Average orders,22,Regular customer
99,119314,420,5,3,19,16.0,No,196,2,1,Soda,77,7,9.0,Regularly busy,Mid-range product,Slowest days,Average orders,22,Regular customer

In [37]:
df_merged['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [41]:
# limit the output to the columns you want
df_merged[['user_id', 'loyalty_flag', 'number_of_orders_by_user', 'max_order']].head(60)

    user_id      loyalty_flag  number_of_orders_by_user  max_order
0         1      New customer                         1         10
1         1      New customer                         2         10
2         1      New customer                         3         10
3         1      New customer                         4         10
4         1      New customer                         5         10
5         1      New customer                         6         10
6         1      New customer                         7         10
7         1      New customer                         8         10
8         1      New customer                         9         10
9         1      New customer                        10         10
10       15  Regular customer                        15         22
11       15  Regular customer                        17         22
12       15  Regular customer                        18         22
13       15  Regular customer                        21         22
14       15  Regular customer                        22         22
15       19      New customer                         2          9
16       19      New customer                         5          9
17       19      New customer                         7          9
18       21  Regular customer                        10         33
19       31  Regular customer                        10         20
20       31  Regular customer                        17         20
21       43  Regular customer                         6         11
22       43  Regular customer                         9         11
23       52  Regular customer                         1         27
24       52  Regular customer                         2         27
25       52  Regular customer                         3         27
26       52  Regular customer                         5         27
27       52  Regular customer                         7         27
28       52  Regular customer                         9         27
29       52  Regular customer                        10         27
30       52  Regular customer                        11         27
31       52  Regular customer                        12         27
32       52  Regular customer                        15         27
33       52  Regular customer                        17         27
34       52  Regular customer                        18         27
35       52  Regular customer                        19         27
36       52  Regular customer                        21         27
37       67  Regular customer                         1         24
38       67  Regular customer                         2         24
39       67  Regular customer                         3         24
40       67  Regular customer                         4         24
41       67  Regular customer                         5         24
42       67  Regular customer                         6         24
43       67  Regular customer                         8         24
44       67  Regular customer                         9         24
45       67  Regular customer                        10         24
46       67  Regular customer                        11         24
47       67  Regular customer                        12         24
48       67  Regular customer                        13         24
49       67  Regular customer                        14         24
50       67  Regular customer                        16         24
51       67  Regular customer                        18         24
52       67  Regular customer                        19         24
53       67  Regular customer                        21         24
54       67  Regular customer                        22         24
55       67  Regular customer                        23         24
56       81      New customer                         3          7
57       81      New customer                         5          7
58       82  Regular customer                         1         19
59       82  Regular customer                         3         19

# Export the Data

In [42]:
df_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_merged_grouped.pkl'))